In [1]:
pip install pandas sqlalchemy pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: pymysql in c:\users\abhishek\appdata\roaming\python\python312\site-packages (1.1.2)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\abhishek\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Requirement already satisfied: six>=1.5 in c:\users\abhishek\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import sqlalchemy

# Connection string format:
# mysql+pymysql://username:password@host:port/database_name

engine = sqlalchemy.create_engine("mysql+pymysql://root:Abhi1326%40@127.0.0.1:3306/ECOMMERCE")

In [3]:
import pandas as pd

# Apna dataset load karo
df = pd.read_excel("C:\\Users\\ABHISHEK\\Desktop\\New Project\\Ecommerce_Data.xlsx")
print(df.head())

        Date Store ID Product ID     Category Region  Inventory Level  \
0 2022-01-01     S001      P0001    Groceries  North              231
1 2022-01-01     S001      P0002         Toys  South              204
2 2022-01-01     S001      P0003         Toys   West              102
3 2022-01-01     S001      P0004         Toys  North              469
4 2022-01-01     S001      P0005  Electronics   East              166

   Units Sold  Units Ordered  Demand Forecast  Price  ...  Revenue Cost Price  \
0         127             55           135.47  33.50  ...  4254.50  17.618033
1         150             66           144.04  63.01  ...  9451.50  39.382828
2          65             51            74.02  27.99  ...  1819.35  14.926337
3          61            164            62.18  32.72  ...  1995.92  17.224692
4          14            135             9.26  73.64  ...  1030.96  62.222790

        Profit  Profit Margin % Price Difference Price Band Demand Gap  \
0  2017.009800        47.408857             3.81     Medium       8.47
1  3544.075757        37.497495            -3.15       High      -5.96
2   849.138077        46.672607            -3.33        Low       9.02
3   945.213778        47.357298            -2.02     Medium       1.18
4   159.840938        15.504087             4.69       High      -4.74

   High Demand Gap Alert Low Sales Alert  Critical Alert
0                  False           False            True
1                  False           False           False
2                  False           False            True
3                  False           False           False
4                  False            True           False

[5 rows x 30 columns]

In [4]:
df.to_sql("retail_cleaned_data", engine, if_exists="replace", index=False)

73100

In [5]:
result = pd.read_sql("Select Count(*) as Total_Records from retail_cleaned_data", engine)
print(result)

   Total_Records
0          73100

In [6]:
## Total Revenue 

Total_Revenue = pd.read_sql("Select sum(Revenue) as Total_Revenue from retail_cleaned_data", engine)
print(Total_Revenue)

   Total_Revenue
0   5.502289e+08

In [7]:
## Total Profit 

Total_Profit = pd.read_sql("Select sum(Profit) as Total_Profit from retail_cleaned_data", engine)
print(Total_Profit)

   Total_Profit
0  1.651438e+08

In [12]:
df.shape

(73100, 30)

In [23]:
# Column names me space ko underscore se replace karo
df.columns = df.columns.str.replace(" ", "_")

# Check updated column names
print(df.columns)

Index(['Date', 'Store_ID', 'Product_ID', 'Category', 'Region',
       'Inventory_Level', 'Units_Sold', 'Units_Ordered', 'Demand_Forecast',
       'Price', 'Discount', 'Weather_Condition', 'Holiday/Promotion',
       'Competitor_Pricing', 'Seasonality', 'Product_Name', 'Month',
       'Month_Num', 'Weekday', 'Quarter', 'Revenue', 'Cost_Price', 'Profit',
       'Profit_Margin_%', 'Price_Difference', 'Price_Band', 'Demand_Gap',
       'High_Demand_Gap_Alert', 'Low_Sales_Alert', 'Critical_Alert'],
      dtype='object')

In [46]:
df.columns = df.columns.str.replace("%", "Pct")

In [47]:
df.to_sql("retail_cleaned_data", engine, if_exists="replace", index=False)

73100

In [48]:
df.columns

Index(['Date', 'Store_ID', 'Product_ID', 'Category', 'Region',
       'Inventory_Level', 'Units_Sold', 'Units_Ordered', 'Demand_Forecast',
       'Price', 'Discount', 'Weather_Condition', 'Holiday/Promotion',
       'Competitor_Pricing', 'Seasonality', 'Product_Name', 'Month',
       'Month_Num', 'Weekday', 'Quarter', 'Revenue', 'Cost_Price', 'Profit',
       'Profit_Margin_Pct', 'Price_Difference', 'Price_Band', 'Demand_Gap',
       'High_Demand_Gap_Alert', 'Low_Sales_Alert', 'Critical_Alert'],
      dtype='object')

In [28]:
## Total Units Sold

units_sold = pd.read_sql("SELECT SUM(Units_Sold) AS Total_Units_Sold FROM retail_cleaned_data;", engine)
print(units_sold)

   Total_Units_Sold
0         9975582.0

In [29]:
### Filter data 

pd.read_sql("Select * from retail_cleaned_data where Revenue > 5000;", engine)

,Date,Store_ID,Product_ID,Category,Region,Inventory_Level,Units_Sold,Units_Ordered,Demand_Forecast,Price,...,Revenue,Cost_Price,Profit,Profit_Margin_%,Price_Difference,Price_Band,Demand_Gap,High_Demand_Gap_Alert,Low_Sales_Alert,Critical_Alert
0,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,...,9451.50,39.382828,3544.075757,37.497495,-3.15,High,-5.96,0,0,0
1,2022-01-01,S001,P0006,Groceries,South,138,128,102,139.82,76.83,...,9834.24,61.578533,1952.187764,19.850927,-2.52,High,11.82,0,0,1
2,2022-01-01,S001,P0008,Clothing,North,380,312,54,329.73,97.99,...,30572.88,85.715858,3829.532153,12.525912,-2.10,Premium,17.73,1,0,0
3,2022-01-01,S001,P0011,Furniture,South,258,150,153,152.74,58.53,...,8779.50,29.938893,4288.666079,48.848637,-2.89,High,2.74,0,0,0
4,2022-01-01,S001,P0015,Clothing,North,379,369,154,363.46,92.99,...,34313.31,68.463190,9050.392851,26.375750,-2.81,Premium,-5.54,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36337,2024-01-01,S005,P0012,Electronics,North,495,324,42,317.46,36.94,...,11968.56,25.442181,3725.293296,31.125660,-1.96,Medium,-6.54,0,0,0
36338,2024-01-01,S005,P0013,Electronics,West,389,276,99,277.27,32.05,...,8845.80,23.113792,2466.393278,27.882083,-3.85,Low,1.27,0,0,0
36339,2024-01-01,S005,P0014,Toys,West,328,190,43,183.97,66.50,...,12635.00,54.084094,2359.022119,18.670535,1.38,High,-6.03,0,0,0
36340,2024-01-01,S005,P0015,Furniture,North,408,323,92,336.64,83.26,...,26892.98,60.319024,7409.935102,27.553418,2.30,Premium,13.64,1,0,0
36341,2024-01-01,S005,P0019,Toys,East,374,264,21,270.52,53.14,...,14028.96,30.601101,5950.269428,42.414188,-2.66,Medium,6.52,0,0,0

In [30]:
### Category wise Revenue 

pd.read_sql("Select Category,sum(Revenue) as Total_Revenue from retail_cleaned_data Group by Category order by Total_Revenue Desc", engine)

      Category  Total_Revenue
0    Furniture   1.115118e+08
1    Groceries   1.109845e+08
2     Clothing   1.096510e+08
3         Toys   1.096424e+08
4  Electronics   1.084391e+08

In [31]:
### Category wise profit 

pd.read_sql("Select Category, sum(Profit) as Total_Profit from retail_cleaned_data Group by Category Order by Total_Profit Desc", engine)

      Category  Total_Profit
0    Furniture  3.331786e+07
1    Groceries  3.324334e+07
2         Toys  3.318791e+07
3     Clothing  3.283236e+07
4  Electronics  3.256237e+07

In [33]:
### Region wise Revenue

pd.read_sql("Select Region, sum(Revenue) as Total_Revenue from retail_cleaned_data Group by Region", engine)

  Region  Total_Revenue
0  North   1.372553e+08
1  South   1.384836e+08
2   West   1.357780e+08
3   East   1.387121e+08

In [34]:
### Top 5 Product 

pd.read_sql("Select Product_name,sum(Revenue) as Revenue from retail_cleaned_data Group by Product_Name Order by Revenue Desc Limit 5", engine)

  Product_name      Revenue
0   Puzzle Set  22901588.37
1   Sugar Pack  22678291.72
2  Cooking Oil  22524940.07
3  Milk Carton  22509683.42
4        Shirt  22491239.68

In [35]:
### Demand Gap 

pd.read_sql("Select Product_Name , Demand_Forecast, Units_Sold,(Demand_Forecast - Units_Sold) as Demand_Gap from retail_cleaned_data Order by Demand_Gap Desc Limit 5", engine)

   Product_Name  Demand_Forecast  Units_Sold  Demand_Gap
0  Office Chair           307.00         287       20.00
1       T-Shirt           134.00         114       20.00
2   Cooking Oil           210.00         190       20.00
3    Puzzle Set           334.00         314       20.00
4    Board Game           194.99         175       19.99

In [39]:
### Monthly Revenue Trend 

pd.read_sql("Select Month, Sum(Revenue) as Monthly_Revenue from retail_cleaned_data Group by Month Order by Month",engine)

        Month  Monthly_Revenue
0       April     1.823581e+07
1      August     1.746549e+07
2    December     3.519748e+08
3    February     1.795917e+07
4     January     1.894133e+07
5        July     1.762630e+07
6        June     1.804893e+07
7       March     1.792905e+07
8         May     1.794707e+07
9    November     1.825860e+07
10    October     1.780468e+07
11  September     1.803766e+07

In [41]:
### Quartery Revenue Trend 

pd.read_sql("Select Quarter, Sum(Revenue) as Quarterly_Revenue from retail_cleaned_data Group by Quarter Order by Quarter",engine)

   Quarter  Quarterly_Revenue
0        1       5.482955e+07
1        2       5.423182e+07
2        3       5.312945e+07
3        4       3.880381e+08

In [49]:
### Avg Profit Margin 

pd.read_sql("Select AVG(Profit_Margin_pct) as Avg_Profit_Margin from retail_cleaned_data",engine)

   Avg_Profit_Margin
0           29.80919

In [57]:
df.columns

Index(['Date', 'Store_ID', 'Product_ID', 'Category', 'Region',
       'Inventory_Level', 'Units_Sold', 'Units_Ordered', 'Demand_Forecast',
       'Price', 'Discount', 'Weather_Condition', 'Holiday/Promotion',
       'Competitor_Pricing', 'Seasonality', 'Product_Name', 'Month',
       'Month_Num', 'Weekday', 'Quarter', 'Revenue', 'Cost_Price', 'Profit',
       'Profit_Margin_Pct', 'Price_Difference', 'Price_Band', 'Demand_Gap',
       'High_Demand_Gap_Alert', 'Low_Sales_Alert', 'Critical_Alert'],
      dtype='object')

In [58]:
## Top product by profit 

pd.read_sql("""
SELECT 
    Product_Name,
    total_profit,
    RANK() OVER (ORDER BY total_profit DESC) AS rank_position
FROM (
    SELECT Product_Name, SUM(Profit) AS total_profit
    FROM retail_cleaned_data
    GROUP BY Product_Name
) t;
""", engine)

      Product_Name  total_profit  rank_position
0       Puzzle Set  6.927596e+06              1
1       Sugar Pack  6.798239e+06              2
2        Bookshelf  6.753059e+06              3
3      Milk Carton  6.738360e+06              4
4           Jacket  6.731121e+06              5
5     Office Chair  6.697169e+06              6
6       Board Game  6.692281e+06              7
7      Cooking Oil  6.681626e+06              8
8         Sofa Set  6.676509e+06              9
9            Shirt  6.667112e+06             10
10    Dining Table  6.656949e+06             11
11   Action Figure  6.614415e+06             12
12      Smartphone  6.590280e+06             13
13     Wheat Flour  6.568220e+06             14
14           Jeans  6.557196e+06             15
15          Laptop  6.552336e+06             16
16         Sweater  6.550839e+06             17
17       Bed Frame  6.534171e+06             18
18  Gaming Console  6.526480e+06             19
19            Doll  6.492184e+06             20
20          LED TV  6.481068e+06             21
21         Toy Car  6.461430e+06             22
22       Rice Pack  6.456898e+06             23
23      Headphones  6.412208e+06             24
24         T-Shirt  6.326093e+06             25

In [59]:
### Running Revenue

pd.read_sql("""
SELECT 
    Month,
    monthly_revenue,
    SUM(monthly_revenue) OVER (ORDER BY Month) AS running_total
FROM (
    SELECT Month, SUM(Revenue) AS monthly_revenue
    FROM retail_cleaned_data
    GROUP BY Month
) t;
""", engine)

        Month  monthly_revenue  running_total
0       April     1.823581e+07   1.823581e+07
1      August     1.746549e+07   3.570131e+07
2    December     3.519748e+08   3.876761e+08
3    February     1.795917e+07   4.056353e+08
4     January     1.894133e+07   4.245766e+08
5        July     1.762630e+07   4.422029e+08
6        June     1.804893e+07   4.602518e+08
7       March     1.792905e+07   4.781809e+08
8         May     1.794707e+07   4.961279e+08
9    November     1.825860e+07   5.143865e+08
10    October     1.780468e+07   5.321912e+08
11  September     1.803766e+07   5.502289e+08

In [63]:
## High Demand Gap Product 

pd.read_sql("""
SELECT 
    Product_Name,
    (Demand_Forecast - Units_Sold) AS demand_gap
FROM retail_cleaned_data
WHERE (Demand_Forecast - Units_Sold) > 10
ORDER BY demand_gap DESC limit 10
""", engine)

   Product_Name  demand_gap
0  Office Chair       20.00
1    Puzzle Set       20.00
2       T-Shirt       20.00
3   Cooking Oil       20.00
4        Laptop       19.99
5     Rice Pack       19.99
6         Jeans       19.99
7   Wheat Flour       19.99
8        LED TV       19.99
9  Dining Table       19.99